name: Codelezz
version: 0.0.1
load: STARTUP
author: Aeltumn
website: https://codelezz.com/#/
main: com.codelezz.spigot.Codelezz
commands:
  codelezz:
    description: Change the function of codelezz.
    aliases: [ code, c ]
    permission-message: You do not have permission to use this command.
    usage: "Usage: /codelezz [reload]"
    permission: codelezz.reload